name: sam3d-objects
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - cuda-toolkit=12.8.1
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.8
  - pip
  - setuptools
  - wheel
  - ninja
  - pytorch3d
  - pip:
      - flash-attn
      - git+https://github.com/NVlabs/nvdiffrast.git
      - git+https://github.com/graphdeco-inria/diff-gaussian-rasterization.git
