name: sam3d-objects
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - setuptools
  - wheel
  - cmake
  - ninja
  - python=3.11
  - cuda-toolkit=12.8.1
  - pytorch
  - torchvision
  - torchaudio
  - pytorch3d
