name: sam3d-objects
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - setuptools<81
  - wheel
  - cmake
  - ninja
  - python=3.11
  - cuda-toolkit=12.8
  - pytorch
  - torchvision
  - torchaudio
