name: sam3d-objects
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pytorch=2.8.*
  - pytorch-cuda=12.8
  - cuda-toolkit=12.8.1
  - pip
  - setuptools
  - wheel
  - cmake
  - ninja
